stages:
  - check
  - test
  - sonar
  - db-migrate
  - deploy
  - release
  - renovate

include:
  - local: .gitlab/ci.gitlab-ci.yml
  - local: .gitlab/sonar.gitlab-ci.yml
  - local: .gitlab/db-migrate.gitlab-ci.yml
  - local: .gitlab/railway-preview.gitlab-ci.yml
  - local: .gitlab/release.gitlab-ci.yml
  - local: .gitlab/renovate.gitlab-ci.yml
  - local: .gitlab/chromatic.gitlab-ci.yml
