workflow:
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /^chore: bump version to/"
      when: never
    - when: always

stages:
  - check
  - test
  - sonar
  - deploy
  - atlas-push
  - atlas-apply
  - version
  - renovate

include:
  - local: .gitlab/ci.gitlab-ci.yml
  - local: .gitlab/sonar.gitlab-ci.yml
  - local: .gitlab/atlas-staging.gitlab-ci.yml
  - local: .gitlab/atlas-prod.gitlab-ci.yml
  - local: .gitlab/railway-preview.gitlab-ci.yml
  - local: .gitlab/version-bump.gitlab-ci.yml
  - local: .gitlab/renovate.gitlab-ci.yml
