version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    command: -url=jdbc:mariadb://mariadb:3306/appdb -user=appuser -password=apppassword -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - mariadb
    networks:
      - app

networks:
  app:

volumes:
  mariadb_data:
