sonar.projectKey=web_brackeys.community_af9b094b-5a03-42d8-8a19-93054eab57f3
sonar.qualitygate.wait=false
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=coverage/**,node_modules/**,dist/**,.output/**,src/routeTree.gen.ts
sonar.cpd.exclusions=coverage/**
