// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  type BinaryReader,
  type BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';

import { CleanupSchedule as __CleanupSchedule } from './cleanup_schedule_type';

export type CleanupOldMessages = {
  arg: __CleanupSchedule;
};

/**
 * A namespace for generated helper functions.
 */
export namespace CleanupOldMessages {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'arg',
        __CleanupSchedule.getTypeScriptAlgebraicType(),
      ),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: CleanupOldMessages,
  ): void {
    CleanupOldMessages.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CleanupOldMessages {
    return CleanupOldMessages.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
