// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  type BinaryReader,
  type BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  type Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  type Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
export type LiveTyping = {
  identity: Identity;
  text: string;
  positionX: number;
  positionY: number;
  isTyping: boolean;
  selectionStart: number;
  selectionEnd: number;
  updatedAt: Timestamp;
  roomCode: string;
};

/**
 * A namespace for generated helper functions.
 */
export namespace LiveTyping {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('identity', AlgebraicType.createIdentityType()),
      new ProductTypeElement('text', AlgebraicType.createStringType()),
      new ProductTypeElement('positionX', AlgebraicType.createF32Type()),
      new ProductTypeElement('positionY', AlgebraicType.createF32Type()),
      new ProductTypeElement('isTyping', AlgebraicType.createBoolType()),
      new ProductTypeElement('selectionStart', AlgebraicType.createU32Type()),
      new ProductTypeElement('selectionEnd', AlgebraicType.createU32Type()),
      new ProductTypeElement('updatedAt', AlgebraicType.createTimestampType()),
      new ProductTypeElement('roomCode', AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: LiveTyping): void {
    LiveTyping.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): LiveTyping {
    return LiveTyping.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
