// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  type BinaryReader,
  type BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  type Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  type Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
export type Room = {
  code: string;
  hostIdentity: Identity;
  passwordHash: string;
  messageTtlSeconds: number;
  messagesEnabled: boolean;
  createdAt: Timestamp;
  lastActivity: Timestamp;
};

/**
 * A namespace for generated helper functions.
 */
export namespace Room {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('code', AlgebraicType.createStringType()),
      new ProductTypeElement(
        'hostIdentity',
        AlgebraicType.createIdentityType(),
      ),
      new ProductTypeElement('passwordHash', AlgebraicType.createStringType()),
      new ProductTypeElement(
        'messageTtlSeconds',
        AlgebraicType.createU32Type(),
      ),
      new ProductTypeElement('messagesEnabled', AlgebraicType.createBoolType()),
      new ProductTypeElement('createdAt', AlgebraicType.createTimestampType()),
      new ProductTypeElement(
        'lastActivity',
        AlgebraicType.createTimestampType(),
      ),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Room): void {
    Room.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Room {
    return Room.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
