// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  type BinaryReader,
  type BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  type Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  type Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
export type SandboxUser = {
  identity: Identity;
  name: string | undefined;
  cursorX: number;
  cursorY: number;
  color: string;
  lastActivity: Timestamp;
  roomCode: string | undefined;
};

/**
 * A namespace for generated helper functions.
 */
export namespace SandboxUser {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('identity', AlgebraicType.createIdentityType()),
      new ProductTypeElement(
        'name',
        AlgebraicType.createOptionType(AlgebraicType.createStringType()),
      ),
      new ProductTypeElement('cursorX', AlgebraicType.createF32Type()),
      new ProductTypeElement('cursorY', AlgebraicType.createF32Type()),
      new ProductTypeElement('color', AlgebraicType.createStringType()),
      new ProductTypeElement(
        'lastActivity',
        AlgebraicType.createTimestampType(),
      ),
      new ProductTypeElement(
        'roomCode',
        AlgebraicType.createOptionType(AlgebraicType.createStringType()),
      ),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SandboxUser): void {
    SandboxUser.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SandboxUser {
    return SandboxUser.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
