// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  type Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  type TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
import type { SandboxUser } from './sandbox_user_type';
import { type EventContext, Reducer, RemoteReducers, RemoteTables } from '.';

/**
 * Table handle for the table `sandbox_user`.
 *
 * Obtain a handle from the [`sandboxUser`] property on [`RemoteTables`],
 * like `ctx.db.sandboxUser`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.sandboxUser.on_insert(...)`.
 */
export class SandboxUserTableHandle {
  tableCache: TableCache<SandboxUser>;

  constructor(tableCache: TableCache<SandboxUser>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SandboxUser> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `identity` unique index on the table `sandbox_user`,
   * which allows point queries on the field of the same name
   * via the [`SandboxUserIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.sandboxUser.identity().find(...)`.
   *
   * Get a handle on the `identity` unique index on the table `sandbox_user`.
   */
  identity = {
    // Find the subscribed row whose `identity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): SandboxUser | undefined => {
      for (const row of this.tableCache.iter()) {
        if (deepEqual(row.identity, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SandboxUser) => void) => {
    return this.tableCache.onInsert(cb);
  };

  removeOnInsert = (cb: (ctx: EventContext, row: SandboxUser) => void) => {
    return this.tableCache.removeOnInsert(cb);
  };

  onDelete = (cb: (ctx: EventContext, row: SandboxUser) => void) => {
    return this.tableCache.onDelete(cb);
  };

  removeOnDelete = (cb: (ctx: EventContext, row: SandboxUser) => void) => {
    return this.tableCache.removeOnDelete(cb);
  };

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SandboxUser, newRow: SandboxUser) => void) => {
    return this.tableCache.onUpdate(cb);
  };

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SandboxUser, newRow: SandboxUser) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  };
}
