atlas-lint-prod:
  stage: atlas-lint
  image: ubuntu:latest
  services:
    - postgres:16
  variables:
    POSTGRES_DB: dev
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl
    - curl -sSf https://atlasgo.sh | sh
  script:
    - atlas migrate lint --dev-url "postgres://user:pass@postgres/dev?sslmode=disable" --dir "file://drizzle" --git-base $CI_MERGE_REQUEST_DIFF_BASE_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

atlas-push-prod:
  stage: atlas-push
  image: ubuntu:latest
  services:
    - postgres:16
  variables:
    POSTGRES_DB: dev
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl
    - curl -sSf https://atlasgo.sh | sh
  script:
    - atlas migrate push brackeys --dev-url "postgres://user:pass@postgres/dev?sslmode=disable" --dir "file://drizzle"
  rules:
    - if: $CI_COMMIT_BRANCH == 'prod'

atlas-apply-prod:
  stage: atlas-apply
  image: ubuntu:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl
    - curl -sSf https://atlasgo.sh | sh
  script:
    - atlas migrate apply --dir "file://drizzle" --url "$PROD_DATABASE_URL" --revisions-schema public
  rules:
    - if: $CI_COMMIT_BRANCH == 'prod'
