atlas-push-staging:
  stage: atlas-push
  image: ubuntu:latest
  services:
    - postgres:16
  variables:
    POSTGRES_DB: dev
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
    ATLAS_TOKEN: $ATLAS_CLOUD_TOKEN
    ATLAS_INPUT_DEV_URL: "postgres://user:pass@postgres/dev?sslmode=disable"
  cache:
    key: atlas-grant-cache
    paths:
      - .atlas/
    policy: pull-push
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl
    - mkdir -p ~/.atlas
    - cp -a $CI_PROJECT_DIR/.atlas/. ~/.atlas/ 2>/dev/null || true
    - curl -sSf https://atlasgo.sh | sh
    - atlas login --token $ATLAS_CLOUD_TOKEN --grant-only
  script:
    - atlas migrate push --dir "file://drizzle" --dir-name brackeys --dev-url "$ATLAS_INPUT_DEV_URL"
  after_script:
    - mkdir -p $CI_PROJECT_DIR/.atlas
    - cp -a ~/.atlas/. $CI_PROJECT_DIR/.atlas/ 2>/dev/null || true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

atlas-apply-staging:
  stage: atlas-apply
  image: ubuntu:latest
  variables:
    ATLAS_TOKEN: $ATLAS_CLOUD_TOKEN
  cache:
    key: atlas-grant-cache
    paths:
      - .atlas/
    policy: pull-push
  artifacts:
    reports:
      dotenv: .env
    paths:
      - .atlas/
    expire_in: 1 day
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl
    - mkdir -p ~/.atlas
    - cp -a $CI_PROJECT_DIR/.atlas/. ~/.atlas/ 2>/dev/null || true
    - curl -sSf https://atlasgo.sh | sh
    - atlas login --token $ATLAS_CLOUD_TOKEN --grant-only
  script:
    - atlas migrate apply --dir "atlas://brackeys" --url "$STAGING_DATABASE_URL" --revisions-schema public --allow-dirty
  after_script:
    - mkdir -p $CI_PROJECT_DIR/.atlas
    - cp -a ~/.atlas/. $CI_PROJECT_DIR/.atlas/ 2>/dev/null || true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
