check:
  stage: check
  image: oven/bun:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - bun install --frozen-lockfile
  script:
    - bun run check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TITLE !~ /^Merge branch/

test:
  stage: test
  image: node:22
  before_script:
    - npm i -g bun
    - bun install --frozen-lockfile
  script:
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'
