check:
  stage: check
  image: oven/bun:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - bun install --frozen-lockfile
  script:
    - bun run check --no-fmt
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'prod'

test:
  stage: test
  image: oven/bun:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - bun install --frozen-lockfile
  script:
    - bun run test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'prod'

build:
  stage: build
  image: oven/bun:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - bun install --frozen-lockfile
  script:
    - bun run build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'prod'
