renovate:
  stage: renovate
  image: renovate/renovate:latest
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: ${CI_API_V4_URL}
    LOG_LEVEL: info
  script:
    - renovate $CI_PROJECT_PATH
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $RENOVATE == "true"
    - if: $CI_PIPELINE_SOURCE == "web" && $RENOVATE == "true"
