-- Seed the skills catalogue ("what the project runs on" — engines,
-- languages, tools) that profiles and collab-post tech stacks draw from.
-- Categories group the pickers; entries a user requested before this seed
-- may already exist by name, so on conflict we only fill in a missing
-- category rather than overwrite a curated one. Idempotent on name.
INSERT INTO "user"."skills" ("name", "category") VALUES
  -- Engines
  ('Godot', 'Engines'),
  ('Unity', 'Engines'),
  ('Unreal Engine', 'Engines'),
  ('GameMaker', 'Engines'),
  ('Construct', 'Engines'),
  ('Defold', 'Engines'),
  ('Bevy', 'Engines'),
  ('MonoGame', 'Engines'),
  ('Phaser', 'Engines'),
  ('LÖVE', 'Engines'),
  ('PICO-8', 'Engines'),
  ('RPG Maker', 'Engines'),
  ('Ren''Py', 'Engines'),
  ('Twine', 'Engines'),
  ('Roblox Studio', 'Engines'),
  -- Languages
  ('C#', 'Languages'),
  ('C++', 'Languages'),
  ('C', 'Languages'),
  ('GDScript', 'Languages'),
  ('Rust', 'Languages'),
  ('Python', 'Languages'),
  ('JavaScript', 'Languages'),
  ('TypeScript', 'Languages'),
  ('Lua', 'Languages'),
  ('Java', 'Languages'),
  ('Go', 'Languages'),
  ('GLSL', 'Languages'),
  ('HLSL', 'Languages'),
  -- Art & Animation
  ('Blender', 'Art & Animation'),
  ('Aseprite', 'Art & Animation'),
  ('Krita', 'Art & Animation'),
  ('Photoshop', 'Art & Animation'),
  ('GIMP', 'Art & Animation'),
  ('Procreate', 'Art & Animation'),
  ('Inkscape', 'Art & Animation'),
  ('Maya', 'Art & Animation'),
  ('ZBrush', 'Art & Animation'),
  ('Substance Painter', 'Art & Animation'),
  ('Spine', 'Art & Animation'),
  ('MagicaVoxel', 'Art & Animation'),
  -- Audio & Music
  ('FMOD', 'Audio & Music'),
  ('Wwise', 'Audio & Music'),
  ('Ableton Live', 'Audio & Music'),
  ('FL Studio', 'Audio & Music'),
  ('REAPER', 'Audio & Music'),
  ('Audacity', 'Audio & Music'),
  ('LMMS', 'Audio & Music'),
  ('Bosca Ceoil', 'Audio & Music'),
  ('Bfxr', 'Audio & Music'),
  -- Frameworks & Libraries
  ('SDL', 'Frameworks & Libraries'),
  ('raylib', 'Frameworks & Libraries'),
  ('libGDX', 'Frameworks & Libraries'),
  ('Pygame', 'Frameworks & Libraries'),
  ('Three.js', 'Frameworks & Libraries'),
  ('Pixi.js', 'Frameworks & Libraries'),
  ('React', 'Frameworks & Libraries'),
  ('Svelte', 'Frameworks & Libraries'),
  ('OpenGL', 'Frameworks & Libraries'),
  ('Vulkan', 'Frameworks & Libraries'),
  -- Backend & Multiplayer
  ('Node.js', 'Backend & Multiplayer'),
  ('PostgreSQL', 'Backend & Multiplayer'),
  ('Firebase', 'Backend & Multiplayer'),
  ('Supabase', 'Backend & Multiplayer'),
  ('PlayFab', 'Backend & Multiplayer'),
  ('Photon', 'Backend & Multiplayer'),
  ('Nakama', 'Backend & Multiplayer'),
  ('Mirror', 'Backend & Multiplayer'),
  ('Netcode for GameObjects', 'Backend & Multiplayer'),
  ('Steamworks', 'Backend & Multiplayer'),
  -- Design & Narrative Tools
  ('Tiled', 'Design & Narrative Tools'),
  ('LDtk', 'Design & Narrative Tools'),
  ('Figma', 'Design & Narrative Tools'),
  ('Ink', 'Design & Narrative Tools'),
  ('Yarn Spinner', 'Design & Narrative Tools'),
  -- Workflow
  ('Git', 'Workflow'),
  ('GitHub', 'Workflow'),
  ('GitLab', 'Workflow'),
  ('Perforce', 'Workflow'),
  ('Unity Version Control', 'Workflow')
ON CONFLICT ("name") DO UPDATE
  SET "category" = EXCLUDED."category"
  WHERE "skills"."category" IS NULL;
