import { addTodo, listTodos } from './todos'
import { getJamData } from './jam'
import {
  getProfile,
  getMyProfile,
  updateProfile,
  syncDiscordData,
  listSkills,
  addUserSkill,
  removeUserSkill,
  requestSkill,
  cancelSkillRequest,
  addProject,
  updateProject,
  removeProject,
  addJamParticipation,
  removeJamParticipation,
  setUrlStub,
} from './profile'
import {
  linkItchIo,
  unlinkItchIo,
  getLinkedAccounts,
  importItchIoGames,
} from './itchio'
import {
  createPost,
  updatePost,
  deletePost,
  closePost,
  reopenPost,
  getPost,
  listPosts,
  featurePost,
  respondToPost,
  listResponses,
  updateResponseStatus,
  listCollabRoles,
  addCollabRole,
  removeCollabRole,
  addPostImage,
  removePostImage,
  reportPost,
  listReports,
  deleteReport,
} from './collab'

export default {
  listTodos,
  addTodo,
  getJamData,
  getProfile,
  getMyProfile,
  updateProfile,
  syncDiscordData,
  listSkills,
  addUserSkill,
  removeUserSkill,
  requestSkill,
  cancelSkillRequest,
  addProject,
  updateProject,
  removeProject,
  addJamParticipation,
  removeJamParticipation,
  setUrlStub,
  linkItchIo,
  unlinkItchIo,
  getLinkedAccounts,
  importItchIoGames,
  createPost,
  updatePost,
  deletePost,
  closePost,
  reopenPost,
  getPost,
  listPosts,
  featurePost,
  respondToPost,
  listResponses,
  updateResponseStatus,
  listCollabRoles,
  addCollabRole,
  removeCollabRole,
  addPostImage,
  removePostImage,
  reportPost,
  listReports,
  deleteReport,
}
