import {
  createPost,
  updatePost,
  deletePost,
  closePost,
  reopenPost,
  getPost,
  listPosts,
  countPostsByType,
  countPostsForJam,
  featurePost,
  respondToPost,
  listResponses,
  updateResponseStatus,
  listCollabRoles,
  addCollabRole,
  removeCollabRole,
  addPostImage,
  removePostImage,
  reportPost,
  listReports,
  deleteReport,
} from "./collab";
import { syncGitHubLink, unlinkGitHub, getContributions } from "./github";
import { linkItchIo, unlinkItchIo, getLinkedAccounts, importItchIoGames } from "./itchio";
import { archiveJams, getJamData, listJams } from "./jam";
import {
  listNotifications,
  unreadCount,
  markRead,
  markAllRead,
  getPreferences,
  updatePreference,
} from "./notifications";
import {
  getProfile,
  getMyProfile,
  updateProfile,
  syncDiscordData,
  listSkills,
  addUserSkill,
  removeUserSkill,
  requestSkill,
  cancelSkillRequest,
  addProject,
  updateProject,
  removeProject,
  addJamParticipation,
  removeJamParticipation,
  setUrlStub,
  listAvailableUsers,
} from "./profile";

export default {
  getJamData,
  listJams,
  archiveJams,
  getProfile,
  getMyProfile,
  updateProfile,
  syncDiscordData,
  listSkills,
  addUserSkill,
  removeUserSkill,
  requestSkill,
  cancelSkillRequest,
  addProject,
  updateProject,
  removeProject,
  addJamParticipation,
  removeJamParticipation,
  setUrlStub,
  listAvailableUsers,
  syncGitHubLink,
  unlinkGitHub,
  getContributions,
  linkItchIo,
  unlinkItchIo,
  getLinkedAccounts,
  importItchIoGames,
  createPost,
  updatePost,
  deletePost,
  closePost,
  reopenPost,
  getPost,
  listPosts,
  countPostsByType,
  countPostsForJam,
  featurePost,
  respondToPost,
  listResponses,
  updateResponseStatus,
  listCollabRoles,
  addCollabRole,
  removeCollabRole,
  addPostImage,
  removePostImage,
  reportPost,
  listReports,
  deleteReport,
  listNotifications,
  unreadCount,
  markRead,
  markAllRead,
  getPreferences,
  updatePreference,
};
