import { describe, expect, it } from "vite-plus/test";

import { runVectors, scriptedRun, VECTORS } from "../../../../../scripts/arcade-determinism.ts";
import { canonicalize, digestOf } from "../../../sim-kit/index.ts";
import { spin, spinSummary } from "../spin.ts";
import golden from "./golden-vectors.json" with { type: "json" };

/**
 * The gate `docs/game-drafts/05-arcade-on-brackeys.md` puts in front of
 * every other arcade milestone.
 *
 * The fixture beside this file was generated by `scripts/arcade-determinism.ts`
 * and verified identical under Bun and Node. That script is also what a
 * browser engine runs for the manual leg of the check; this test is the leg
 * that runs on every commit, so a sim change that moves a result cannot land
 * unnoticed.
 *
 * If this fails, the question is not "is the fixture stale". It is: does
 * this change mean to invalidate every stored run and leaderboard entry
 * validated against the old numbers? If yes, bump `sim_version`, regenerate
 * with `--write`, and say so in the commit. If no, the change is a bug.
 */
describe("cross-engine determinism", () => {
  it("reproduces the committed golden vectors", () => {
    expect(runVectors()).toEqual(golden);
  });

  it("covers every vector the fixture claims", () => {
    expect(golden.vectors.map((v) => v.name)).toEqual([
      ...VECTORS.map((v) => v.name),
      "scripted run / twelve tables",
    ]);
  });

  it("replays a whole run to the same tables, the way the validator will", () => {
    // The run vector is the only one that exercises the table loop: the
    // quota check, the imprisoned stakes, and the nudge allowance draining
    // across spins.
    expect(scriptedRun("en-prison:golden:run")).toEqual(scriptedRun("en-prison:golden:run"));
  });

  it("ends the scripted run somewhere real", () => {
    const played = scriptedRun("en-prison:golden:run");
    expect(["cleared", "busted"]).toContain(played.run.status);
    expect(played.tables).toHaveLength(played.run.tables.length);
    expect(played.tables.length).toBeGreaterThan(0);
  });

  it("gives every vector its own result", () => {
    const digests = golden.vectors.map((v) => v.digest);
    expect(new Set(digests).size).toBe(digests.length);
  });

  it("re-simulates a vector to the same summary, the way the validator will", () => {
    for (const vector of VECTORS) {
      const first = spinSummary(spin(vector.wheel, vector.input, vector.seed));
      const second = spinSummary(spin(vector.wheel, vector.input, vector.seed));
      expect(digestOf(second)).toBe(digestOf(first));
    }
  });

  it("rejects a summary that has been edited, which is the whole point", () => {
    const vector = VECTORS[0]!;
    const honest = spinSummary(spin(vector.wheel, vector.input, vector.seed));
    const forged = { ...honest, returned: honest.returned + 1000 };
    expect(digestOf(forged)).not.toBe(digestOf(honest));
  });

  it("holds nothing but integers in a summary", () => {
    // `canonicalize` refuses a float, so this is also the check that no
    // stage has started returning one.
    for (const vector of VECTORS) {
      expect(() =>
        canonicalize(spinSummary(spin(vector.wheel, vector.input, vector.seed))),
      ).not.toThrow();
    }
  });
});
