/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GameRouteImport } from './routes/game'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as CollabIndexRouteImport } from './routes/collab.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as GameRoomIdRouteImport } from './routes/game/$roomId'
import { Route as CollabNewRouteImport } from './routes/collab.new'
import { Route as CollabPostIdRouteImport } from './routes/collab.$postId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as OauthItchioCallbackRouteImport } from './routes/oauth.itchio.callback'
import { Route as OauthGithubCallbackRouteImport } from './routes/oauth.github.callback'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const CollabIndexRoute = CollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => GameRoute,
} as any)
const CollabNewRoute = CollabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollabRoute,
} as any)
const CollabPostIdRoute = CollabPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CollabRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthItchioCallbackRoute = OauthItchioCallbackRouteImport.update({
  id: '/oauth/itchio/callback',
  path: '/oauth/itchio/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGithubCallbackRoute = OauthGithubCallbackRouteImport.update({
  id: '/oauth/github/callback',
  path: '/oauth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collab': typeof CollabRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/game': typeof GameRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/collab/': typeof CollabIndexRoute
  '/game/': typeof GameIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/collab': typeof CollabIndexRoute
  '/game': typeof GameIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collab': typeof CollabRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/game': typeof GameRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/collab/': typeof CollabIndexRoute
  '/game/': typeof GameIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collab'
    | '/command-center'
    | '/game'
    | '/profile'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/profile/$userId'
    | '/collab/'
    | '/game/'
    | '/profile/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/profile/$userId'
    | '/collab'
    | '/game'
    | '/profile'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
  id:
    | '__root__'
    | '/'
    | '/collab'
    | '/command-center'
    | '/game'
    | '/profile'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/profile/$userId'
    | '/collab/'
    | '/game/'
    | '/profile/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollabRoute: typeof CollabRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  GameRoute: typeof GameRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  OauthGithubCallbackRoute: typeof OauthGithubCallbackRoute
  OauthItchioCallbackRoute: typeof OauthItchioCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/collab/': {
      id: '/collab/'
      path: '/'
      fullPath: '/collab/'
      preLoaderRoute: typeof CollabIndexRouteImport
      parentRoute: typeof CollabRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/collab/new': {
      id: '/collab/new'
      path: '/new'
      fullPath: '/collab/new'
      preLoaderRoute: typeof CollabNewRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/$postId': {
      id: '/collab/$postId'
      path: '/$postId'
      fullPath: '/collab/$postId'
      preLoaderRoute: typeof CollabPostIdRouteImport
      parentRoute: typeof CollabRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/itchio/callback': {
      id: '/oauth/itchio/callback'
      path: '/oauth/itchio/callback'
      fullPath: '/oauth/itchio/callback'
      preLoaderRoute: typeof OauthItchioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/github/callback': {
      id: '/oauth/github/callback'
      path: '/oauth/github/callback'
      fullPath: '/oauth/github/callback'
      preLoaderRoute: typeof OauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollabRouteChildren {
  CollabPostIdRoute: typeof CollabPostIdRoute
  CollabNewRoute: typeof CollabNewRoute
  CollabIndexRoute: typeof CollabIndexRoute
}

const CollabRouteChildren: CollabRouteChildren = {
  CollabPostIdRoute: CollabPostIdRoute,
  CollabNewRoute: CollabNewRoute,
  CollabIndexRoute: CollabIndexRoute,
}

const CollabRouteWithChildren =
  CollabRoute._addFileChildren(CollabRouteChildren)

interface GameRouteChildren {
  GameRoomIdRoute: typeof GameRoomIdRoute
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameRoomIdRoute: GameRoomIdRoute,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollabRoute: CollabRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  GameRoute: GameRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  OauthGithubCallbackRoute: OauthGithubCallbackRoute,
  OauthItchioCallbackRoute: OauthItchioCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
