/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OgprobeRouteImport } from './routes/ogprobe'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembersRouteImport } from './routes/members'
import { Route as JamsRouteImport } from './routes/jams'
import { Route as GameRouteImport } from './routes/game'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as JamsIndexRouteImport } from './routes/jams.index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as CollabIndexRouteImport } from './routes/collab.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMotionRouteImport } from './routes/settings.motion'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects.$projectSlug'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as OgSplatRouteImport } from './routes/og.$'
import { Route as JamsJamSlugRouteImport } from './routes/jams_.$jamSlug'
import { Route as JamsCalendarRouteImport } from './routes/jams.calendar'
import { Route as JamsArchiveRouteImport } from './routes/jams.archive'
import { Route as ImagesSplatRouteImport } from './routes/images.$'
import { Route as GameRoomIdRouteImport } from './routes/game/$roomId'
import { Route as CollabNewRouteImport } from './routes/collab.new'
import { Route as CollabPostIdRouteImport } from './routes/collab.$postId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ProjectsGameGameIdRouteImport } from './routes/projects.game.$gameId'
import { Route as OauthItchioCallbackRouteImport } from './routes/oauth.itchio.callback'
import { Route as OauthGithubCallbackRouteImport } from './routes/oauth.github.callback'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiNotificationsUnsubRouteImport } from './routes/api.notifications.unsub'
import { Route as ApiNotificationsStreamRouteImport } from './routes/api.notifications.stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicRpcSplatRouteImport } from './routes/api.public.rpc.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OgprobeRoute = OgprobeRouteImport.update({
  id: '/ogprobe',
  path: '/ogprobe',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsRoute = JamsRouteImport.update({
  id: '/jams',
  path: '/jams',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const JamsIndexRoute = JamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JamsRoute,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const CollabIndexRoute = CollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMotionRoute = SettingsMotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsJamSlugRoute = JamsJamSlugRouteImport.update({
  id: '/jams_/$jamSlug',
  path: '/jams/$jamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const JamsCalendarRoute = JamsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => JamsRoute,
} as any)
const JamsArchiveRoute = JamsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => JamsRoute,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => GameRoute,
} as any)
const CollabNewRoute = CollabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollabRoute,
} as any)
const CollabPostIdRoute = CollabPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CollabRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGameGameIdRoute = ProjectsGameGameIdRouteImport.update({
  id: '/projects/game/$gameId',
  path: '/projects/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthItchioCallbackRoute = OauthItchioCallbackRouteImport.update({
  id: '/oauth/itchio/callback',
  path: '/oauth/itchio/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGithubCallbackRoute = OauthGithubCallbackRouteImport.update({
  id: '/oauth/github/callback',
  path: '/oauth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsUnsubRoute = ApiNotificationsUnsubRouteImport.update({
  id: '/api/notifications/unsub',
  path: '/api/notifications/unsub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsStreamRoute = ApiNotificationsStreamRouteImport.update({
  id: '/api/notifications/stream',
  path: '/api/notifications/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRpcSplatRoute = ApiPublicRpcSplatRouteImport.update({
  id: '/api/public/rpc/$',
  path: '/api/public/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/collab': typeof CollabRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/game': typeof GameRouteWithChildren
  '/jams': typeof JamsRouteWithChildren
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/ogprobe': typeof OgprobeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/teams': typeof TeamsRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/images/$': typeof ImagesSplatRoute
  '/jams/archive': typeof JamsArchiveRoute
  '/jams/calendar': typeof JamsCalendarRoute
  '/jams/$jamSlug': typeof JamsJamSlugRoute
  '/og/$': typeof OgSplatRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/motion': typeof SettingsMotionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/collab/': typeof CollabIndexRoute
  '/game/': typeof GameIndexRoute
  '/jams/': typeof JamsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unsub': typeof ApiNotificationsUnsubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
  '/projects/game/$gameId': typeof ProjectsGameGameIdRoute
  '/api/public/rpc/$': typeof ApiPublicRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/command-center': typeof CommandCenterRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/ogprobe': typeof OgprobeRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/images/$': typeof ImagesSplatRoute
  '/jams/archive': typeof JamsArchiveRoute
  '/jams/calendar': typeof JamsCalendarRoute
  '/jams/$jamSlug': typeof JamsJamSlugRoute
  '/og/$': typeof OgSplatRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/motion': typeof SettingsMotionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/collab': typeof CollabIndexRoute
  '/game': typeof GameIndexRoute
  '/jams': typeof JamsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unsub': typeof ApiNotificationsUnsubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
  '/projects/game/$gameId': typeof ProjectsGameGameIdRoute
  '/api/public/rpc/$': typeof ApiPublicRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/collab': typeof CollabRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/game': typeof GameRouteWithChildren
  '/jams': typeof JamsRouteWithChildren
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/ogprobe': typeof OgprobeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/teams': typeof TeamsRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/collab/$postId': typeof CollabPostIdRoute
  '/collab/new': typeof CollabNewRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/images/$': typeof ImagesSplatRoute
  '/jams/archive': typeof JamsArchiveRoute
  '/jams/calendar': typeof JamsCalendarRoute
  '/jams_/$jamSlug': typeof JamsJamSlugRoute
  '/og/$': typeof OgSplatRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/motion': typeof SettingsMotionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/collab/': typeof CollabIndexRoute
  '/game/': typeof GameIndexRoute
  '/jams/': typeof JamsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unsub': typeof ApiNotificationsUnsubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/oauth/github/callback': typeof OauthGithubCallbackRoute
  '/oauth/itchio/callback': typeof OauthItchioCallbackRoute
  '/projects/game/$gameId': typeof ProjectsGameGameIdRoute
  '/api/public/rpc/$': typeof ApiPublicRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/collab'
    | '/command-center'
    | '/feed.xml'
    | '/game'
    | '/jams'
    | '/members'
    | '/notifications'
    | '/ogprobe'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/suspended'
    | '/teams'
    | '/terms'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/images/$'
    | '/jams/archive'
    | '/jams/calendar'
    | '/jams/$jamSlug'
    | '/og/$'
    | '/profile/$userId'
    | '/projects/$projectSlug'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/motion'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/teams/$teamId'
    | '/collab/'
    | '/game/'
    | '/jams/'
    | '/profile/'
    | '/settings/'
    | '/teams/'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/notifications/unsub'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
    | '/projects/game/$gameId'
    | '/api/public/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/command-center'
    | '/feed.xml'
    | '/members'
    | '/notifications'
    | '/ogprobe'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suspended'
    | '/terms'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/images/$'
    | '/jams/archive'
    | '/jams/calendar'
    | '/jams/$jamSlug'
    | '/og/$'
    | '/profile/$userId'
    | '/projects/$projectSlug'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/motion'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/teams/$teamId'
    | '/collab'
    | '/game'
    | '/jams'
    | '/profile'
    | '/settings'
    | '/teams'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/notifications/unsub'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
    | '/projects/game/$gameId'
    | '/api/public/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/collab'
    | '/command-center'
    | '/feed.xml'
    | '/game'
    | '/jams'
    | '/members'
    | '/notifications'
    | '/ogprobe'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/suspended'
    | '/teams'
    | '/terms'
    | '/api/$'
    | '/collab/$postId'
    | '/collab/new'
    | '/game/$roomId'
    | '/images/$'
    | '/jams/archive'
    | '/jams/calendar'
    | '/jams_/$jamSlug'
    | '/og/$'
    | '/profile/$userId'
    | '/projects/$projectSlug'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/motion'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/teams/$teamId'
    | '/collab/'
    | '/game/'
    | '/jams/'
    | '/profile/'
    | '/settings/'
    | '/teams/'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/notifications/unsub'
    | '/api/rpc/$'
    | '/oauth/github/callback'
    | '/oauth/itchio/callback'
    | '/projects/game/$gameId'
    | '/api/public/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  CollabRoute: typeof CollabRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  GameRoute: typeof GameRouteWithChildren
  JamsRoute: typeof JamsRouteWithChildren
  MembersRoute: typeof MembersRoute
  NotificationsRoute: typeof NotificationsRoute
  OgprobeRoute: typeof OgprobeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuspendedRoute: typeof SuspendedRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  JamsJamSlugRoute: typeof JamsJamSlugRoute
  OgSplatRoute: typeof OgSplatRoute
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationsStreamRoute: typeof ApiNotificationsStreamRoute
  ApiNotificationsUnsubRoute: typeof ApiNotificationsUnsubRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  OauthGithubCallbackRoute: typeof OauthGithubCallbackRoute
  OauthItchioCallbackRoute: typeof OauthItchioCallbackRoute
  ProjectsGameGameIdRoute: typeof ProjectsGameGameIdRoute
  ApiPublicRpcSplatRoute: typeof ApiPublicRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogprobe': {
      id: '/ogprobe'
      path: '/ogprobe'
      fullPath: '/ogprobe'
      preLoaderRoute: typeof OgprobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams': {
      id: '/jams'
      path: '/jams'
      fullPath: '/jams'
      preLoaderRoute: typeof JamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/jams/': {
      id: '/jams/'
      path: '/'
      fullPath: '/jams/'
      preLoaderRoute: typeof JamsIndexRouteImport
      parentRoute: typeof JamsRoute
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/collab/': {
      id: '/collab/'
      path: '/'
      fullPath: '/collab/'
      preLoaderRoute: typeof CollabIndexRouteImport
      parentRoute: typeof CollabRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/motion': {
      id: '/settings/motion'
      path: '/motion'
      fullPath: '/settings/motion'
      preLoaderRoute: typeof SettingsMotionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams_/$jamSlug': {
      id: '/jams_/$jamSlug'
      path: '/jams/$jamSlug'
      fullPath: '/jams/$jamSlug'
      preLoaderRoute: typeof JamsJamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jams/calendar': {
      id: '/jams/calendar'
      path: '/calendar'
      fullPath: '/jams/calendar'
      preLoaderRoute: typeof JamsCalendarRouteImport
      parentRoute: typeof JamsRoute
    }
    '/jams/archive': {
      id: '/jams/archive'
      path: '/archive'
      fullPath: '/jams/archive'
      preLoaderRoute: typeof JamsArchiveRouteImport
      parentRoute: typeof JamsRoute
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/collab/new': {
      id: '/collab/new'
      path: '/new'
      fullPath: '/collab/new'
      preLoaderRoute: typeof CollabNewRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/$postId': {
      id: '/collab/$postId'
      path: '/$postId'
      fullPath: '/collab/$postId'
      preLoaderRoute: typeof CollabPostIdRouteImport
      parentRoute: typeof CollabRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/game/$gameId': {
      id: '/projects/game/$gameId'
      path: '/projects/game/$gameId'
      fullPath: '/projects/game/$gameId'
      preLoaderRoute: typeof ProjectsGameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/itchio/callback': {
      id: '/oauth/itchio/callback'
      path: '/oauth/itchio/callback'
      fullPath: '/oauth/itchio/callback'
      preLoaderRoute: typeof OauthItchioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/github/callback': {
      id: '/oauth/github/callback'
      path: '/oauth/github/callback'
      fullPath: '/oauth/github/callback'
      preLoaderRoute: typeof OauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/unsub': {
      id: '/api/notifications/unsub'
      path: '/api/notifications/unsub'
      fullPath: '/api/notifications/unsub'
      preLoaderRoute: typeof ApiNotificationsUnsubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/stream': {
      id: '/api/notifications/stream'
      path: '/api/notifications/stream'
      fullPath: '/api/notifications/stream'
      preLoaderRoute: typeof ApiNotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rpc/$': {
      id: '/api/public/rpc/$'
      path: '/api/public/rpc/$'
      fullPath: '/api/public/rpc/$'
      preLoaderRoute: typeof ApiPublicRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollabRouteChildren {
  CollabPostIdRoute: typeof CollabPostIdRoute
  CollabNewRoute: typeof CollabNewRoute
  CollabIndexRoute: typeof CollabIndexRoute
}

const CollabRouteChildren: CollabRouteChildren = {
  CollabPostIdRoute: CollabPostIdRoute,
  CollabNewRoute: CollabNewRoute,
  CollabIndexRoute: CollabIndexRoute,
}

const CollabRouteWithChildren =
  CollabRoute._addFileChildren(CollabRouteChildren)

interface GameRouteChildren {
  GameRoomIdRoute: typeof GameRoomIdRoute
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameRoomIdRoute: GameRoomIdRoute,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface JamsRouteChildren {
  JamsArchiveRoute: typeof JamsArchiveRoute
  JamsCalendarRoute: typeof JamsCalendarRoute
  JamsIndexRoute: typeof JamsIndexRoute
}

const JamsRouteChildren: JamsRouteChildren = {
  JamsArchiveRoute: JamsArchiveRoute,
  JamsCalendarRoute: JamsCalendarRoute,
  JamsIndexRoute: JamsIndexRoute,
}

const JamsRouteWithChildren = JamsRoute._addFileChildren(JamsRouteChildren)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsMotionRoute: typeof SettingsMotionRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsMotionRoute: SettingsMotionRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  CollabRoute: CollabRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  GameRoute: GameRouteWithChildren,
  JamsRoute: JamsRouteWithChildren,
  MembersRoute: MembersRoute,
  NotificationsRoute: NotificationsRoute,
  OgprobeRoute: OgprobeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuspendedRoute: SuspendedRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  JamsJamSlugRoute: JamsJamSlugRoute,
  OgSplatRoute: OgSplatRoute,
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationsStreamRoute: ApiNotificationsStreamRoute,
  ApiNotificationsUnsubRoute: ApiNotificationsUnsubRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  OauthGithubCallbackRoute: OauthGithubCallbackRoute,
  OauthItchioCallbackRoute: OauthItchioCallbackRoute,
  ProjectsGameGameIdRoute: ProjectsGameGameIdRoute,
  ApiPublicRpcSplatRoute: ApiPublicRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
