/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */

export type GetGuildsGuildIdInfractionsType =
  (typeof GetGuildsGuildIdInfractionsType)[keyof typeof GetGuildsGuildIdInfractionsType];

export const GetGuildsGuildIdInfractionsType = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
} as const;
