/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */
import type { GetGuildsGuildIdInfractionsType } from './getGuildsGuildIdInfractionsType';

export type GetGuildsGuildIdInfractionsParams = {
  /**
   * Filter by user ID
   */
  userId?: string;
  /**
   * Filter by infraction type
   */
  type?: GetGuildsGuildIdInfractionsType;
  /**
   * Maximum number of results to return
   */
  limit?: string;
  /**
   * Number of results to skip
   */
  offset?: string;
};
