/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */
import type { Infraction } from './infraction';

export type GetGuildsGuildIdUsersUserIdInfractions200 = {
  success?: boolean;
  data?: Infraction[];
};
