/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */

/**
 * 0: Warning, 1: Mute, 2: Kick, 3: Ban
 */
export type InfractionType = typeof InfractionType[keyof typeof InfractionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InfractionType = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
} as const;
