/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */
import type { InfractionType } from './infractionType';

export interface Infraction {
  id?: string;
  guildId?: string;
  userId?: string;
  /** 0: Warning, 1: Mute, 2: Kick, 3: Ban */
  type?: InfractionType;
  reason?: string;
  moderatorId?: string;
  createdAt?: string;
}
