/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hammer API
 * API for managing Brackeys Discord community data including rules, infractions, and member notes
 * OpenAPI spec version: 1.0.0
 */

export interface Rule {
  id?: string;
  guildId?: string;
  title?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}
