// This file is auto-generated by @hey-api/openapi-ts

export const $Error = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean',
            example: false
        },
        error: {
            type: 'string',
            example: 'Error message'
        }
    }
} as const;

export const $HealthCheck = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            example: 'ok'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            example: '2025-05-08T23:17:35-05:00'
        }
    }
} as const;

export const $Rule = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123456789'
        },
        guildId: {
            type: 'string',
            example: '987654321'
        },
        title: {
            type: 'string',
            example: 'Be respectful'
        },
        description: {
            type: 'string',
            example: 'Treat everyone with respect.'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $Infraction = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123456789'
        },
        guildId: {
            type: 'string',
            example: '987654321'
        },
        userId: {
            type: 'string',
            example: '876543210'
        },
        type: {
            type: 'string',
            example: '0',
            enum: ['0', '1', '2', '3'],
            description: '0: Warning, 1: Mute, 2: Kick, 3: Ban'
        },
        reason: {
            type: 'string',
            example: 'Violated rule #1'
        },
        moderatorId: {
            type: 'string',
            example: '765432109'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $MemberNote = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123456789'
        },
        guildId: {
            type: 'string',
            example: '987654321'
        },
        userId: {
            type: 'string',
            example: '876543210'
        },
        content: {
            type: 'string',
            example: 'User was helpful in the #help channel'
        },
        authorId: {
            type: 'string',
            example: '765432109'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;