name: 'Chromatic'

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Storybook
        run: |
          echo "Building Storybook..."
          bun run build-storybook
          echo "Build complete. Checking output directory..."
          ls -la storybook-static || echo "storybook-static directory not found!"
          if [ -f "storybook-static/index.html" ]; then
            echo "✅ index.html found - build successful"
          else
            echo "❌ index.html not found - build may have failed"
            exit 1
          fi

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
