name: Deploy to Preview Channel

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      VITE_SPACETIME_HOST: ${{ secrets.SPACETIME_HOST }}
      VITE_SPACETIME_MODULE: ${{ secrets.SPACETIME_MODULE }}
      VITE_SPACETIME_ROOM_KEY: ${{ secrets.SPACETIME_ROOM_KEY }}
      VITE_BRACKEYS_GUILD_ID: ${{ secrets.BRACKEYS_GUILD_ID }}
      VITE_HASURA_GRAPHQL_URL: ${{ secrets.HASURA_GRAPHQL_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile && bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 3d
          projectId: brackeys-web
